#!/usr/bin/env bash
#
# build-sysroot.sh — assemble and validate the minixrs sysroot (roadmap P3):
#
#   1. build + install musl (scripts/build-musl.sh) unless --skip-musl
#   2. sanity-check the installed layout (docs/sysroot-layout.md)
#   3. ABI selftest: compile minixrs' generated abi-selftest.c against the
#      installed headers, POSIX errno block armed
#   4. link a static hello world with a plain driver invocation, then verify it
#      is branded (check-brand.sh) and loadable (check-image.sh)
#
# Step 4's link line *is* the M3 claim:
#
#     clang --target=aarch64-unknown-minixrs hello.c -o hello
#
# and nothing else — no -T, no -L, no hand-fed compiler_builtins. Anything that
# has to be added back here is a toolchain bug to fix in the fork, not a flag to
# paper over it with.
#
# The hello ELF is installed at $MINIXRS_SDK/share/minixrs/hello — minixrs
# sessions use it as a canned exec-test artifact (M3 gate).
#
# Usage: build-sysroot.sh [--skip-musl]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
. "$SCRIPT_DIR/env.sh"

CLANG="$MINIXRS_SDK/bin/clang"
TRIPLE=aarch64-unknown-minixrs
SYSROOT="$MINIXRS_SDK/sysroot"
ABI_SELFTEST_C="$MINIXRS_GEN_C_HEADERS_DIR/abi-selftest.c"

SKIP_MUSL=0
[ "${1:-}" = "--skip-musl" ] && SKIP_MUSL=1

if [ ! -x "$CLANG" ]; then
    echo "build-sysroot: $CLANG not found — run scripts/build-llvm.sh first" >&2
    exit 1
fi

if [ "$SKIP_MUSL" -eq 0 ]; then
    "$SCRIPT_DIR/build-musl.sh"
fi

# ------------------------------------------------------------------ [1/3]
echo "build-sysroot: [1/3] installed layout"
for f in usr/lib/libc.a usr/lib/crt1.o usr/lib/crti.o usr/lib/crtn.o \
         usr/include/stdio.h usr/include/minixrs/ipc.h .stamp; do
    if [ ! -f "$SYSROOT/$f" ]; then
        echo "build-sysroot: missing $SYSROOT/$f — musl install incomplete?" >&2
        echo "build-sysroot: run scripts/build-musl.sh (without --skip-musl)" >&2
        exit 1
    fi
done
echo "build-sysroot: PASS layout ($(cat "$SYSROOT/.stamp"))"

# ------------------------------------------------------------------ [2/3]
# The D7 errno check, for real. -nostdinc is what makes it honest: the host
# libc must not creep in (Darwin's EDEADLK is 11, musl's is 35), so the values
# compared are the fork's own bits/errno.h against the live kernel-shared
# constants the generator read.
#
# MINIXRS_ABI_SELFTEST overrides the whole command if minixrs moves the CLI.
echo "build-sysroot: [2/3] ABI selftest"
if [ -n "${MINIXRS_ABI_SELFTEST:-}" ]; then
    if eval "$MINIXRS_ABI_SELFTEST"; then
        echo "build-sysroot: PASS ABI selftest (MINIXRS_ABI_SELFTEST override)"
    else
        echo "build-sysroot: FAIL ABI selftest (MINIXRS_ABI_SELFTEST override)" >&2
        exit 1
    fi
else
    if [ ! -f "$ABI_SELFTEST_C" ]; then
        cat >&2 <<EOF
build-sysroot: $ABI_SELFTEST_C not found

It is generated by minixrs' gen-c-headers, which scripts/build-musl.sh runs and
leaves beside the musl build — on the forks volume by default. Recover with:

    scripts/forks-volume.sh mount   # if the volume is merely unmounted
    scripts/build-musl.sh           # regenerates them, rebuilding if needed

or set MINIXRS_ABI_SELFTEST to your own command. This gate is not skipped: a
sysroot whose errno values have drifted from the ABI is exactly what it exists
to catch.
EOF
        exit 1
    fi
    "$CLANG" --target="$TRIPLE" \
        -nostdinc -isystem "$SYSROOT/usr/include" \
        -DMINIXRS_ABI_CHECK_POSIX_ERRNO \
        -std=c11 -pedantic-errors -Wall -Wextra -Werror -fsyntax-only \
        "$ABI_SELFTEST_C"
    echo "build-sysroot: PASS ABI selftest ($ABI_SELFTEST_C)"
fi

# ------------------------------------------------------------------ [3/3]
# compiler-rt supplies the quad-float builtins musl's vfprintf needs
# (aarch64 long double is IEEE quad). Checking for the archive up front turns
# an undefined-__multf3 link error into an actionable message.
RESOURCE_DIR="$("$CLANG" --target="$TRIPLE" -print-resource-dir)"
BUILTINS="$RESOURCE_DIR/lib/$TRIPLE/libclang_rt.builtins.a"
if [ ! -f "$BUILTINS" ]; then
    echo "build-sysroot: $BUILTINS not found" >&2
    echo "build-sysroot: run scripts/build-compiler-rt.sh — musl's vfprintf needs" >&2
    echo "build-sysroot: the quad-float builtins (__multf3, __floatsitf, …)" >&2
    exit 1
fi

echo "build-sysroot: [3/3] link and verify a branded hello world"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cat > "$tmp/hello.c" <<'EOF'
#include <stdio.h>

int main(void)
{
    printf("hello from the minixrs sysroot\n");
    return 0;
}
EOF

# No --sysroot, no -static, no -L: the driver defaults to all three for this
# triple. Keeping the line bare is the point of the milestone.
"$CLANG" --target="$TRIPLE" -o "$tmp/hello" "$tmp/hello.c"

HELLO_INSTALLED="$MINIXRS_SDK/share/minixrs/hello"

# A hello that fails either check is not installed — and neither is an older one
# left in place. The installed artifact is a claim about *this* sysroot, so
# leaving a stale binary that still passes both checks would quietly hand
# minixrs sessions something built by a toolchain that no longer exists.
reject() { # <what went wrong>
    echo "build-sysroot: $1" >&2
    if [ -f "$HELLO_INSTALLED" ]; then
        rm -f "$HELLO_INSTALLED"
        echo "build-sysroot: removed the stale $HELLO_INSTALLED" >&2
    fi
    exit 1
}

if ! "$REPO_ROOT/verify/check-brand.sh" "$tmp/hello"; then
    reject "the linked image is not correctly branded (see above; the brand comes from musl's crt1.o)"
fi
if ! "$REPO_ROOT/verify/check-image.sh" "$tmp/hello"; then
    reject "the linked image violates the kernel loader's rules (see above; docs/plans/musl-m3.md tracks the open ones)"
fi

mkdir -p "$MINIXRS_SDK/share/minixrs"
cp "$tmp/hello" "$HELLO_INSTALLED"
echo "build-sysroot: branded hello installed at $HELLO_INSTALLED"
